### ISSUE TITLE
並行して衝突する ltx batch blind write が aomaly を起こしている。

### ISSUE THREAD

**Issue by thawk105** [project-tsurugi/shirakami#131]
## 概要
並行して衝突する ltx batch blind write が aomaly を起こしている。
初期値: (key(int), value) = (1, 0), (2, 0)
ltx1 が (1, "1"), (2, "1") という値で書き込み、
ltx2 が (1, "2"), (2, "2") という値で書き込んだら、
結果がねじれて (1, "1"), (2, "2") という結果のようになることがある。
（テストファイルではより多くのページ数をターゲットにし、トランザクションをループさせて複数回一定時間動作させている）

## 再現手順

https://github.com/project-tsurugi/shirakami/actions/runs/7176060317/job/19540351772

long_concurrent_batch_upsert_test.cpp をパラメーター調整しながら実行する。

## 影響
blind write で non serializable なスケジューリングを許容してしまう。

## 期待する動作
上述した事象を発現させない。

**Comment by thawk105** [comment]
事象の発生事由：
書き込むときに１ページずつしかロックしていないため、追い越しが発生する。

対策に関して：
blind write では、他ltx に対する read wait をしないために後置を強制する。
書き込み先のタイムスタンプとして、ltx は tx id を付与するようにし、後置の際は優先度が高いものを最新とする。（なるべくIWR を適用させる）
そうすることで、低優先度が高優先度を追い越しても(A)いずれ高優先度が上書きして(B)一貫した状態にする。

それらを低優先度ｌｔｘが観測したらどうなるか？
少なくとも、高優先度ltx 側は生存中で wp が他者から観測可能であり、それを観測して boundary wait をする。
(B) によって衝突判定は衝突した扱いになり、(A) を読んでいた（ねじれていた）ら、RUB 違反で弾ける。

**Comment by thawk105** [comment]
memo

前置のグループと後置のグループをどのように弁別可能なのか？

後置のグループの順序決めに関して。
後から始まったものを後ろにするとIWRが効かないけど待ちが無い。
先に始まったものを後ろにするとIWRが効くが待ちがある。

**Comment by thawk105** [comment]
> 同一エポックにおいて、前置のグループと後置のグループをどのように弁別可能なのか？

（前置のグループ）
一度でも waiting bypass していたり、boundary wait の結果衝突していたら、前置。

（後置のグループ）
一度も waiting bypass せず、boundary wait の結果が衝突していない（前置していない）ならば、ltx の開始順にバージョンオーダーを合わせる。換言すると、後から始まったものを後ろにする。

決めごとを上記にしたいと考えています。動機としては、IWR が効きにくくても待ちが無いことを有益に考えたからです。
そのようなとき、例題においてどのような振る舞いになるかを説明したく存じます。

例:

前提条件:
初期状態: (key, value) = (1, "0"), (2, "0)

先に始まったtx vs 後に始まったtx

blind write ltx (A) vs blind write ltx (B)
Q_1: 二つの blind writes ltx A, B があり、A, B の順序に開始するとする。 A は (1, "1"), (2, "1") を書くもので、B は (1, "2"), (2, "2") を書くものとしたときに、最終的に(1, "1"), (2, "2") のようにねじれないか？
A_1: 後置のグループとして ltx の開始順に並べるため、最終状態は (1, "2"), (2, "2") になるためねじれない。
Q_1_1: 他 LTX からねじれた状態を観測されないか？
A_1_1: 観測されたときは RUB 違反で弾ける。二つの blind writes ltx が位置するエポックを n としたとき、それらを観測していたｌｔｘは最終的に衝突した判定になってエポック n に対して前置することと、エポック n のバージョンを読んでしまっているから。

blind write ltx (A) vs read write ltx (B)
BがAの書き込み先を読んでいたり、他Txに対して前置しているならばAに対して前置するし、そうでないならば制約に従って後置する。

read write ltx (A) vs blind write ltx (B)
blind write ltx は後置するから待たずに書ける。

read write ltx (A) vs read write ltx (B)
BがAにぶつかっているならばAに対して前置するし、そうでないならば後置する。

**Comment by okachimachiorz** [comment]
特に異論はない。ただし
以下のケースで

blind write ltx (A) vs read write ltx (B)
read write ltx (A) vs blind write ltx (B)
read write ltx (A) vs read write ltx (B)

それぞれ3パターンについては、Txの開始順とCommit順の2x2で4通りがそれぞれあるので、
4通りx3＝12のテストは書いたほうがよいです
テストの挙動が不安ならこちらでreviewします。
@thawk105

**Comment by thawk105** [comment]
現在の shirakami master branch で期待されない振る舞いをする問題は解決したと思われる。

イシューとしては解決とし、新たに enhancement label で下記コメントに関するテスト補強を扱う。
https://github.com/project-tsurugi/shirakami/issues/131#issuecomment-1851847125
