### ISSUE TITLE
concurrent running ltx がいなかったときに、 ltx id を初期化する。

### ISSUE THREAD

**Issue by thawk105** [project-tsurugi/shirakami#73]
概要: ltx id は長期で走り続ければいずれラップアラウンドする。それを回避するために、クリア可能な機会を設え、その機会にクリアする。

タスクリスト
- [ ] read by が現状 unique かつ単調増加に ltx id が発行されることを前提とする代わりに効率の良い設計になっており、これが read by 登録・削除・検証の作りへ影響を与える問題になる。
- [ ] ltx id が単調増加になっていることを前提としている仕様・作りに関して調査し、直すべきところをリスト化する。
- [ ] 上記リスト化に対して作業する。

工数見積もり：数日

**Comment by thawk105** [comment]
ltx id は上位コンポーネントに影響を与えない。例えば上位コンポーネントとやり取りする tx id 関連の情報は session id, session に閉じた tx counter, それのラップラウンド回数の三つの情報で生成される。

任意のグローバル情報の管理に ltx id の単調増加が影響しているかを調査する必要あり。

**Comment by kuron99** [comment]
https://github.com/project-tsurugi/tsurugi-issues/issues/696 と同件であれば、そちらで扱うことにしてもいいかもしれません。

**Comment by thawk105** [comment]
@kuron99 id が大きくなって一部の入れ物であふれるかもしれないから、それをどうするかというイシュー (tsurugi-issues 696) と、id が大きくなったら（ラップラウンドを防ぐために）カウントを初期化するというのは似て異なる問題に感じます。

例えば、後者は閾値として前者の溢れそうな値を設定すれば、後者を実現すると前者の問題を防げますが、同一の問題処理かと言われると疑問に感じるところです...

**Comment by kuron99** [comment]
「あふれるかもしれない」という問題があってそれが696で、その解決方として「カウントを初期化する」という本issueがあるという状況ではないでしょうか？だとすると 696は本issueを包含しているといえませんか？696を解決しようとすると本issueの方向も選択肢の一つとなると。タスク管理上は問題意識のあるところに集約した方がやりやすそうな気がするので、696の解決案の一つとして本issueを参照しつつ、こちらは閉じて696に合流させてもいいのかなと思いました。

**Comment by thawk105** [comment]
696 に合流させてしまっても良い気がしました。本イシューをクローズし、逆参照を貼ろうと思います。
